services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticket_sales
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  bot:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: ticket_bot
    depends_on:
      - postgres
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DATABASE_URL: ${DATABASE_URL:postgresql+asyncpg://postgres:postgres@postgres:5432/ticket_sales}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticket_sales
      POSTGRES_HOST: postgres
    command: poetry run python -m bot.main
    volumes:
      - ..:/app
    working_dir: /app
    restart: unless-stopped

volumes:
  postgres_data: