"""Add cover_path to events

Revision ID: c8a566773883
Revises: 562b405dcdbc
Create Date: 2025-04-26 14:35:26.460159

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8a566773883"
down_revision: Union[str, None] = "562b405dcdbc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("cover_path", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "cover_path")
    # ### end Alembic commands ###
